# Generated by Django 5.2.4 on 2025-08-15 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название теста')),
                ('is_trial', models.BooleanField(default=False, verbose_name='Пробный тест')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tests/items/', verbose_name='Фото с заданиями')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='testing.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Фото-вопрос',
                'verbose_name_plural': 'Фото-вопросы',
                'ordering': ['test', 'order'],
                'unique_together': {('test', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Метка (A–D)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='testing.photoquestion', verbose_name='Фото-вопрос')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
                'ordering': ['label'],
                'unique_together': {('question', 'label')},
            },
        ),
    ]
