# Generated by Django 5.2.4 on 2025-08-15 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photoquestion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='photoquestion',
            name='test',
        ),
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tests/pages/', verbose_name='Изображение страницы')),
                ('page_number', models.PositiveIntegerField(default=1, verbose_name='Номер страницы')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='testing.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Страница теста',
                'verbose_name_plural': 'Страницы теста',
                'ordering': ['test', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(verbose_name='Номер вопроса')),
                ('correct_option', models.CharField(choices=[('A', 'А'), ('B', 'Б'), ('C', 'В'), ('D', 'Г')], max_length=1, verbose_name='Правильный вариант')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.testpage', verbose_name='Страница теста')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['question_number'],
                'unique_together': {('page', 'question_number')},
            },
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='PhotoQuestion',
        ),
    ]
